In [17]:
import numpy as np

#zad 1
# macierz A z zadania
A = np.array([[2, 1, 1], 
             [1, 3, 6],
             [4, 5, 5]])
# macierz B z zadania
B = np.array([[1, 0 ,5],
             [2, 1, 6],
             [0, 3, 0]])
# wyświetlenie macierzy A i B
print(A)
print("    x\n",B,"\n     =")

def mul(A, B):
    # pusta macierz wynikowa
    C = np.zeros((len(A),len(B[0])))
    # sprawdza czy liczba kolumn pierwszej macierzy rowna sie liczbie wierszy drugiej
    if len(B) == len(A[0]): 
        for x in range(len(A)): # przechodzimy przez wiersze macierzy A
            for y in range(len(B[0])): # przechodzimy przez kolumny macierzy B
                for z in range(len(B)): # z kolumn macierzy B bierzemy wiersze
                    C[x][y] += A[x,z] * B[z,y] # mnożymy po kolei elementy wiersza macierzy A z elementami 
                                               # danej kolumny macierzy B
        return C # zwracamy wynik
                
    else: 
        # jeżeli warunek mnożenia macierzy nie jest spełniony wyświetl błąd
        print("Macierze A i B nie mogą być pomnożone")
    
# wyświetlamy wynik końcowy zwrócony z funkcji
print(mul(A,B))

[[2 1 1]
 [1 3 6]
 [4 5 5]]
    x
 [[1 0 5]
 [2 1 6]
 [0 3 0]] 
     =
[[ 4.  4. 16.]
 [ 7. 21. 23.]
 [14. 20. 50.]]


In [18]:
#zad 2 
# macierz A z zadania
A = np.array([[1,  4, 5],
             [2, 1, 6],
             [0, 3 ,2]])

def det(A):
    if len(A) == len(A[0]): # sprawdzamy czy macierz ma wymiary 3x3
        # wyliczamy wyznacznik zgodnie ze wzorem Cramera
        d = (A[0][0]* (A[1][1]*A[2][2] - A[1][2] * A[2][1]))- (A[0][1]* (A[1][0]*A[2][2] - A[1][2]*A[2][0])) + A[0][2]* (A[1][0]*A[2][1] - A[1][1]*A[2][0])
        return d # zwracamy wyliczony wyznacznik
    else:
        return "Podałeś inną macierz niż 3x3" # jeżeli macierz ma inne wymiary niż 3x3 zwracamy komunikat

# wyświetlamy wynik końcowy zwrócony z funkcji
print(det(A))

-2


In [19]:
#zad 3 
# macierz A z zadania
A = np.array([[3, 2, 4, 1, 8, 0],
             [2, 3, 5, 6, 0, 3],
             [7, 7, 2, 1, 4, 5]])

def tran(A):
    # tworzymy nową macierz z zamienionymi wierszami i kolumnami do transpozycji
    T = np.zeros((len(A[0]),len(A)))
    for x in range(len(A)): # przechodzimy przez wiersze
        for y in range(len(A[0])): # przechodzimy przez kolumny
            T[y][x] = A[x][y] # do nowo utworzonej macierzy przypisujemy elementy macierzy A na odwrót
    return T # zwracamy macierz po transpozycji

# wyświetlamy wynik końcowy zwrócony z funkcji
print(tran(A))

[[3. 2. 7.]
 [2. 3. 7.]
 [4. 5. 2.]
 [1. 6. 1.]
 [8. 0. 4.]
 [0. 3. 5.]]
