In [14]:
# zad 1

import numpy as np

A = np.array([[8, 1, 4, 2, 1],
             [8, 6, 4, 2, 1],
             [1, 2, 3, 4, 1],
             [8, 0, 6, 2, 5],
             [1, 9, 6, 4, 1]])

def inv(A):
    # tworzymy macierz jednostkową na bazie macierzy A
    id = np.eye(len(A))
    # wyznaczamy macierz rozszerzoną, będącą połączeniem macierzy A oraz odpowiadającej jej macierzy jednostkowej
    cA = np.concatenate((A, id), axis=1) 
    # przechodzimy przez wiersze macierzy                                     
    for x in range(len(A)): 
        # tworzymy zmienną odpowiedzialną za kolumny
        y = 1
        # wyznaczamy wartość przekątnej
        diag = cA[x][x] 
        # szukamy niezerowego współczynnika
        while x + y < len(A):
            # zamieniamy wiersze
            cA[[x, x + y]] = cA[[x + y, x]]
            # wyznaczanmy nowy współczynnik przekątnej
            diag = cA[x][x] 
            y += 1
        # bierzemy rząd i dzielimy w celu otrzymania 1 na przekątnej 
        cA[x] /= diag
        # przechodzimy przez rzędy omijając przekątną
        for y in [k for k in range(len(A)) if k != x]: 
            # odejmujemy obecny rząd od pozostałych
            cA[y] -= cA[x] * cA[y][x] 
    # zwracamy macierz odwrotna pozbywając się przeksztalconej macierzy jednostkowej
    return cA[:, len(A):] 

print("A*A^(-1)=\n", np.around(((inv(A)@A)),decimals=0))
print("Macierz odwrotna liczona ręcznie:\n", inv(A))
print("Macierz odwrotna liczona za pomocą np:\n", np.linalg.inv(A))

A*A^(-1)=
 [[ 1. -0. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0.  0.]
 [-0. -0.  0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]
Macierz odwrotna liczona ręcznie:
 [[ 1.33333333e-02  1.36666667e-01  3.33333333e-02 -1.66666667e-02
  -1.00000000e-01]
 [-2.00000000e-01  2.00000000e-01 -1.24900090e-16 -2.77555756e-17
   2.28983499e-16]
 [ 4.66666667e-01 -4.66666667e-01 -3.33333333e-01  8.32667268e-17
   3.33333333e-01]
 [-1.20000000e-01  1.45000000e-01  4.50000000e-01 -5.83333333e-02
  -1.83333333e-01]
 [-5.33333333e-01  2.83333333e-01  1.66666667e-01  2.50000000e-01
  -1.66666667e-01]]
Macierz odwrotna liczona za pomocą np:
 [[ 1.33333333e-02  1.36666667e-01  3.33333333e-02 -1.66666667e-02
  -1.00000000e-01]
 [-2.00000000e-01  2.00000000e-01  2.50191104e-17 -2.77555756e-18
   0.00000000e+00]
 [ 4.66666667e-01 -4.66666667e-01 -3.33333333e-01  4.47874061e-18
   3.33333333e-01]
 [-1.20000000e-01  1.45000000e-01  4.50000000e-01 -5.83333333e-02
  -1.83333333e-01]
 [-5.33333333e-01  2.83333333e-0

In [13]:
# zad 1 zle

import numpy as np

A = np.array([[8, 1, 4, 2, 1],
             [8, 6, 4, 2, 1],
             [1, 2, 3, 4, 1],
             [8, 0, 6, 2, 5],
             [1, 9, 6, 4, 1]])

def inv(A):
    id = np.eye(len(A))
    cid = id.copy().astype('float')
    cA = A.copy().astype('float')
    for x in range(len(A)):
        val = 1/A[x][x]
        for y in range(len(A[0])):
            cA[x][y] *= val
            cid[x][y] *= val
        for k in range(len(A)):
            temp = cA[k][x]
            for j in range(len(A[0])):
                if k!=j:
                    cA[k][j] -=  temp * cA[x][j]
                    cid[k][j] -=  temp * cid[x][j]
                    
            

                
#     print("macierz ktora powinna byc jednostkowa:\n",cA)
    return cid


print("Macierz odwrotna wlasna:\n", inv(A))
print("a se przemnoze v2\n", inv(A)@A)
print("Macierz odwrotna z np:\n", np.linalg.inv(A))

Macierz odwrotna wlasna:
 [[0.125      0.         0.         0.         0.        ]
 [0.         0.16666667 0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.5        0.        ]
 [0.         0.         0.         0.         1.        ]]
a se przemnoze v2
 [[1.         0.125      0.5        0.25       0.125     ]
 [1.33333333 1.         0.66666667 0.33333333 0.16666667]
 [0.33333333 0.66666667 1.         1.33333333 0.33333333]
 [4.         0.         3.         1.         2.5       ]
 [1.         9.         6.         4.         1.        ]]
Macierz odwrotna z np:
 [[ 1.33333333e-02  1.36666667e-01  3.33333333e-02 -1.66666667e-02
  -1.00000000e-01]
 [-2.00000000e-01  2.00000000e-01  2.50191104e-17 -2.77555756e-18
   0.00000000e+00]
 [ 4.66666667e-01 -4.66666667e-01 -3.33333333e-01  4.47874061e-18
   3.33333333e-01]
 [-1.20000000e-01  1.45000000e-01  4.50000000e-01 -5.83333333e-02
  -1.83333333e-01]
 [-5.3333