In [13]:
# zad 1
import numpy as np

A = np.array([[3, 6],
             [0, 9]])
B = np.array([[-3, -9],
             [1, 3]])

def inv2x2(A):
    det = A[0,0] * A[1,1] - A[0,1] * A[1,0]
    if det == 0:
        return "wyznacznik podanej macierzy wynosi 0"
    
    AD = np.zeros((len(A),len(A[0])))
    AD[0][0] = A[1][1]
    AD[0][1] = A[1][0] * (-1)
    AD[1][0] = A[0][1] * (-1)
    AD[1][1] = A[0][0]
    
    ADT = np.zeros((len(A[0]),len(A)))
    for x in range(len(A)):
        for y in range(len(A[0])):
            ADT[y][x] = AD[x][y]
            
    I = ADT/det  
    return I

print("a)")
print("Z własnej funkcji:\n",inv2x2(A))
print("Z gotowej funkcji:\n",np.linalg.inv(A))

print("\n b)")
print("Z własnej funkcji:\n",inv2x2(B))
print("Z gotowej funkcji:\n")
print(np.linalg.inv(B))


a)
Z własnej funkcji:
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]
Z gotowej funkcji:
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]

 b)
Z własnej funkcji:
 wyznacznik podanej macierzy wynosi 0
Z gotowej funkcji:



LinAlgError: Singular matrix

In [15]:
# zad 2

A2 = np.array([[1, 0, 5],
              [2, 7, 6],
              [8, 3, 2]])
B2 = np.array([[3, -1, 1],
              [5, 1, 4],
              [-1, 3, 2]])

def inv3x3(A):
    det = (A[0][0]* (A[1][1]*A[2][2] - A[1][2] * A[2][1]))- (A[0][1]* (A[1][0]*A[2][2] - A[1][2]*A[2][0])) + A[0][2]* (A[1][0]*A[2][1] - A[1][1]*A[2][0])
    if det == 0:
        return "wyznacznik podanej macierzy wynosi 0"
    
    T = np.zeros((len(A[0]),len(A)))
    for x in range(len(A)):
        for y in range(len(A[0])):
            T[y][x] = A[x][y]
    
    AD = np.zeros((len(A),len(A[0])))
    AD[0][0] = T[1][1] * T[2][2] - T[1][2] * T[2][1]
    AD[0][1] = T[1][0] * T[2][2] - T[1][2] * T[2][0] * (-1)
    AD[0][2] = T[1][0] * T[2][1] - T[1][1] * T[2][0]
    AD[1][0] = T[0][1] * T[2][2] - T[0][2] * T[2][1] * (-1)
    AD[1][1] = T[0][0] * T[2][2] - T[0][2] * T[2][0]
    AD[1][2] = T[0][0] * T[2][1] - T[0][1] * T[2][0] * (-1)
    AD[2][0] = T[0][1] * T[1][2] - T[0][2] * T[1][1]
    AD[2][1] = T[0][0] * T[1][2] - T[0][2] * T[0][1] * (-1)
    AD[2][2] = T[0][0] * T[1][1] - T[0][1] * T[1][0]
    
    I = AD/det
    return I

print("a)")
print("Z własnej funkcji:\n",inv3x3(A2))
print("Z gotowej funkcji:\n",np.linalg.inv(A2))

print("\n b)")
print("Z własnej funkcji:\n",inv3x3(B2))
print("Z gotowej funkcji:\n",np.linalg.inv(B2))

a)
Z własnej funkcji:
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.20472441  0.1496063  -0.06299213]
 [ 0.19685039 -0.07480315 -0.02755906]]
Z gotowej funkcji:
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]

 b)
Z własnej funkcji:
 wyznacznik podanej macierzy wynosi 0
Z gotowej funkcji:
 [[ 1.40737488e+15 -7.03687442e+14  7.03687442e+14]
 [ 1.97032484e+15 -9.85162418e+14  9.85162418e+14]
 [-2.25179981e+15  1.12589991e+15 -1.12589991e+15]]


In [23]:
# zad 3

def inv(A):
    if len(A) != len(A[0]):
        return "macierz nie jest kwadratowa"
    if len(A) == 2:
        return inv2x2(A)
    if len(A) == 3:
        return inv3x3(A)
    else:
        return "podaj macierz o wymiarach 2x2 lub 3x3"

print("1a Z własnej funkcji:\n ", inv(A))
print("\nZ gotowej funkcji:\n",np.linalg.inv(A))

1a Z własnej funkcji:
  [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]

Z gotowej funkcji:
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]


In [22]:
print("1b Z własnej funkcji:\n ", inv(B))
print("Z gotowej funkcji:\n")
print(np.linalg.inv(B))

1b Z własnej funkcji:
  wyznacznik podanej macierzy wynosi 0
Z gotowej funkcji:



LinAlgError: Singular matrix

In [18]:
print("2a Z własnej funkcji:\n ", inv(A2))
print("\nZ gotowej funkcji:\n",np.linalg.inv(A2))

2a Z własnej funkcji:
  [[ 0.01574803 -0.05905512  0.13779528]
 [-0.20472441  0.1496063  -0.06299213]
 [ 0.19685039 -0.07480315 -0.02755906]]

Z gotowej funkcji:
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]


In [19]:
print("2b Z własnej funkcji:\n ", inv(B2))
print("\nZ gotowej funkcji:\n",np.linalg.inv(B2))

2b Z własnej funkcji:
  wyznacznik podanej macierzy wynosi 0

Z gotowej funkcji:
 [[ 1.40737488e+15 -7.03687442e+14  7.03687442e+14]
 [ 1.97032484e+15 -9.85162418e+14  9.85162418e+14]
 [-2.25179981e+15  1.12589991e+15 -1.12589991e+15]]
