In [29]:
import numpy as np

#zad1
vec = np.array([1, 4, 5, 6, 2, 1, 5, 6, 7, 8])
print("Vector: ",vec)

vec = np.delete(vec, 5)
print("Deleted index 5: ",vec)

vec = np.append(vec, [8])
print("Append 8: ",vec)

for x in range(len(vec)):
    if x%2 == 1:
        vec[x] +=2
print("Odd index +2: ",vec)

vec = np.flip(vec)
print("Flipped vec:", vec)

Vector:  [1 4 5 6 2 1 5 6 7 8]
Deleted index 5:  [1 4 5 6 2 5 6 7 8]
Append 8:  [1 4 5 6 2 5 6 7 8 8]
Odd index +2:  [ 1  6  5  8  2  7  6  9  8 10]
Flipped vec: [10  8  9  6  7  2  8  5  6  1]


In [30]:
#zad2
"""
Mnozenie wektora powstałego za pomocą numpya przez skalar różni się od mnożenia listy przez skalar tym, że w przypadku
mnożenia listy przez skalar elementy są powielane. Natomiast w przypadku arraya numpya wartości elementów sa mnożone.
"""

vec = np.array([4, 4, 4, 4, 4])
li = [1, 2, 3, 4 ,5]
scalar = 3
vec = scalar * vec
print("Multiplication using numpy array:\n",vec)
li = scalar * li
print("Multiplication using python list\n",li)

Multiplication using numpy array:
 [12 12 12 12 12]
Multiplication using python list
 [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [31]:
#zad3
matrix = np.array([[3, 5, 0],[2, 6, 1],[3, 8, 9]])
print(matrix)

matrix[0,0] = -2
print("First element changed to -2:\n", matrix)

matrix[1,1] = 44
print("Element in middle changed to 44:\n", matrix)

matrix[2,2] = 0
print("Last element changed to 0:\n", matrix)

[[3 5 0]
 [2 6 1]
 [3 8 9]]
First element changed to -2:
 [[-2  5  0]
 [ 2  6  1]
 [ 3  8  9]]
Element in middle changed to 44:
 [[-2  5  0]
 [ 2 44  1]
 [ 3  8  9]]
Last element changed to 0:
 [[-2  5  0]
 [ 2 44  1]
 [ 3  8  0]]


In [32]:
#zad4

for x in range(len(matrix)):
    for y in range(len(matrix[0])):
        if (x%2 == 0) and (y%2 == 0):
            matrix[x,y] = 0
print("Even indexes changed to 0:\n", matrix)

Even indexes changed to 0:
 [[ 0  5  0]
 [ 2 44  1]
 [ 0  8  0]]


In [33]:
#zad5

matrix1 = np.array([[2, 1, 1],[1, 3, 6],[4, 5, 5]])
matrix2 = np.array([[1, 0, 5],[2, 1, 6],[0, 3, 0]])
matrix3 = np.copy(matrix1)
print(matrix1)
print("    +\n",matrix2)

for x in range(len(matrix)):
    for y in range(len(matrix[0])):
        matrix3[x,y] = matrix1[x,y] + matrix2[x,y]
print("    =\n",matrix3)

[[2 1 1]
 [1 3 6]
 [4 5 5]]
    +
 [[1 0 5]
 [2 1 6]
 [0 3 0]]
    =
 [[ 3  1  6]
 [ 3  4 12]
 [ 4  8  5]]


In [34]:
#zad6

import tensorflow as tf

"""
shape=(4,4) - tensor o rozmiarze 4x4
dtype=int32 - wartości tego tensora są 32-bitowymi liczbami calkowitymi
numpy=array - jest to reprezentacja macierzy numpyowskiej
"""
t = tf.constant([[1, 2, 3 ,4],[1, 2, 3, 4],[1, 2, 3, 4], [1, 2, 3, 4]])
t



<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])>